### ISSUE TITLE
Fix visualization generation feature

### ISSUE THREAD

**Issue by varchanaiyer** [dev-vishnuprasad/Insight_Generator#1]
![image](https://github.com/user-attachments/assets/59a49b5f-45bb-417b-a5bc-1d63aaf1bc77)
The application currently doesn't generate visualizations as expected. Debug and fix this feature to ensure graphs and plots are correctly produced and displayed for uploaded datasets.

**Comment by dev-vishnuprasad** [comment]
Yes mam, It is a known issue it  takes a fair amount of time to generate
insights as generating histograms, training multiple classification models
and making a api call to the gemini and waiting for the response all done
in a single go.

[image: image.png]
Kindly check the output folder of the project after clicking on the
generate insights. If you can see the generated visualizations on the
output folder then the application is working as intended  and kindly wait
for the page to fully load

The fully loaded page should look like this

[image: image.png]

If the visualizations are not generated on the output folder Please reply
and I'll look into it.
